version: '3'
services:
  flask-react-app:
    image: jacksonlabs/flask-react-app:local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    
  react-app:
    image: jacksonlabs/react-app:local-infra
    build:
      context: ../react-app/
      dockerfile: Dockerfile
      args:
        # build a production package (true) or (false) 
        - BUILD=true

    # Volume only required for hot reloading in development mode
    volumes:
      - "../react-app/app/public:/app/public:ro"
      - "../react-app/app/src:/app/src:ro"

    environment:
      - HOST=0.0.0.0
      - PORT=3000

      # node (development) or (production) environment
      - NODE_ENV=production

  flask-app:
    image: jacksonlabs/flask-app:local-infra
    build:
      context: ../flask-app/
      dockerfile: Dockerfile

    # Volume only required for hot reloading in flask development mode
    volumes:
      - "../flask-app/app:/app:ro"

    environment:
      - ADDRESS=0.0.0.0
      - PORT=5000

      # execution mode (flask) or (gunicorn) defaults to gunicorn
      - MODE=gunicorn

      # flask (development) or (production) modes
      - FLASK_ENV=production

      # gunicorn debug on (1) or off (0) defaults to 0
      - DEBUG_MODE=0
