version: '3'
services:
  flask-app-nginx:
    image: jacksonlabs/flask-app-nginx:local
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:5000

  flask-app:
    image: jacksonlabs/flask-app:local
    build:
      context: .
      dockerfile: Dockerfile

    # Volume only required for hot reloading in flask development mode
    volumes:
      - "./app:/app:ro"

    environment:
      - ADDRESS=0.0.0.0
      - PORT=5000

      # execution mode (flask) or (gunicorn), defaults to gunicorn if MODE not set
      - MODE=flask

      # flask (development) or (production) modes
      - FLASK_ENV=development

      # gunicorn debug on (1) or off (0) defaults to 0
      - DEBUG_MODE=0
